Feat/jiva 99/restore from snapshot
mesoform/Multi-Cloud-Platform-Foundations pull request #11
Opened 2022-08-25 22:03 UTC by dgavrischuk

2022-08-27 12:35 UTC, gbmeuk requested changes

2022-08-27 12:35 UTC, gbmeuk commented on AWS/snapshot_recovery/script/restore.sh
> +AZ="eu-central-1a"
Shouldn't this be a variable? Also, only zone is needed because region can be extracted from zone.

2022-08-27 12:35 UTC, gbmeuk commented on AWS/snapshot_recovery/script/restore.sh
> +OLDVOLUMEID=$(aws ec2 describe-instances --filters Name=instance-id,Values=$INSTANCEID | jq  ".Reservations[].Instances[].BlockDeviceMappings[] | {DeviceName: .DeviceName, VolumeId: .Ebs.VolumeId}" |
I think device name will need to be a variable, unless it can be parsed from `instanceDescribe`

2022-09-09 21:06 UTC, gbmeuk requested changes

2022-09-09 21:06 UTC, gbmeuk commented on AWS/snapshot_recovery/script/restore.sh
> +#!/usr/bin/env bash
this script looks fine but please add it to a directory called `DR`, in https://github.com/mesoform/Multi-Cloud-Platform and call the script `vm_snapshot_recovery.sh`

2022-09-22 10:27 UTC, AlexBMes commented on AWS/snapshot_recovery/script/restore.sh
> +#!/usr/bin/env bash
If the script was moved to the [Multi-Cloud-Platform](https://github.com/mesoform/Multi-Cloud-Platform/tree/master/DR) repository, is it necessary to have it in this repository as well? 
It might be worth having a README with an explanation of what the script is for and how to use?

2022-09-25 18:56 UTC, closed without merging