Feat/jiva 98/cost anomaly controls
mesoform/Multi-Cloud-Platform-Foundations pull request #15
Opened 2022-09-20 09:25 UTC by dgavrischuk

2022-09-22 10:51 UTC, AlexBMes requested changes
See inline comments

2022-09-22 10:51 UTC, AlexBMes commented on AWS/anomaly_monitor/providers.tf
> +provider "aws" {
Provider block probably shouldn't be included (see [comment in other PR](https://github.com/mesoform/Multi-Cloud-Platform-Foundations/pull/14#discussion_r977500799))

2022-09-22 10:51 UTC, AlexBMes commented on AWS/anomaly_monitor/vars.tf
> +  default = "dmytro.gavryschuk@mesoform.com"
Remove default variable with personal info

2022-09-25 18:59 UTC, gbmeuk commented on AWS/snapshot_recovery/script/restore.sh
> +#!/usr/bin/env bash
remove this script

2022-09-25 19:09 UTC, closed without merging