Cloud DNS Record Set module
mesoform/Multi-Cloud-Platform-Foundations pull request #19
Opened 2022-10-14 10:26 UTC by AlexBMes

Module for adding DNS records for a specified Google managed DNS zone

2022-10-16 22:16 UTC, gbmeuk requested changes

2022-10-16 22:16 UTC, gbmeuk commented on Google/resource-manager/cloud_dns_records/locals.tf
> +  cloud_dns_records_yml = fileexists(var.cloud_dns_records_yml) ? file(var.cloud_dns_records_yml) : null
Lets call this domains/zones instead of records.

2022-10-16 22:16 UTC, gbmeuk commented on Google/resource-manager/cloud_dns_records/locals.tf
> +  cloud_dns_record_sets = {
This can then be domain_records or zone_records

2022-10-16 22:16 UTC, gbmeuk commented on Google/resource-manager/cloud_dns_records/resources/records.tf
> +      dynamic geo{
Fee minor formatting issues fixed with IDE autocorrect

2022-10-16 22:16 UTC, gbmeuk commented on Google/resource-manager/cloud_dns_records/resources/vars.tf
> +    type    = optional(string, "A")
Should this be here?

2022-10-17 07:28 UTC, AlexBMes commented on Google/resource-manager/cloud_dns_records/locals.tf
> +  cloud_dns_records_yml = fileexists(var.cloud_dns_records_yml) ? file(var.cloud_dns_records_yml) : null
Updated in [commit](https://github.com/mesoform/Multi-Cloud-Platform-Foundations/pull/19/commits/e8739cd3b8d9a50f76b1927ae913584200a373b0)

2022-10-17 07:29 UTC, AlexBMes commented on Google/resource-manager/cloud_dns_records/resources/records.tf
> +      dynamic geo{
Updated in [commit](https://github.com/mesoform/Multi-Cloud-Platform-Foundations/pull/19/commits/d88178e570028500e41ec5c26ef34651388b980a)

2022-10-17 07:33 UTC, AlexBMes commented on Google/resource-manager/cloud_dns_records/resources/vars.tf
> +    type    = optional(string, "A")
Removed attribute as it was unused

2022-10-17 09:06 UTC, gbmeuk approved these changes

2022-10-17 16:00 UTC, merged