feat/PS-96/sa_module
mesoform/Multi-Cloud-Platform-Foundations pull request #27
Opened 2023-01-09 18:36 UTC by danperezsan

Test: https://protraderseco.atlassian.net/browse/PS-96?focusedCommentId=10483

2023-01-09 18:43 UTC, gbmeuk requested changes
Automated tests, not comments.

2023-01-10 18:57 UTC, danperezsan commented
Added unit and deployment tests

2023-01-10 19:01 UTC, danperezsan commented
On the Setup Cloud SDK step for the deployment test the service account seems to need a new auth token:
```
Error: google-github-actions/setup-gcloud failed with: failed to execute command `gcloud --quiet auth activate-service-account githubactions-mcp-deploy@protean-buffer-230514.iam.gserviceaccount.com --key-file -`: ERROR: (gcloud.auth.activate-service-account) There was a problem refreshing your current auth tokens: ('invalid_grant: Invalid JWT Signature.', ***'error': 'invalid_grant', 'error_description': 'Invalid JWT Signature.'***)
```

2023-01-10 19:48 UTC, gbmeuk requested changes

2023-01-10 19:48 UTC, gbmeuk commented on tests/gcp/unit_tests/google_service_account/main.tf
> +data external test_disabled {
Can we test getting an IAM conditions field instead. That's a more complex algorithm.

2023-01-10 19:48 UTC, gbmeuk commented on tests/gcp/unit_tests/google_service_account/test_iam_bindings_count.py
> +    'test_account_count' : '1',
Not useful to test the same value. Best practice is extremes and somewhere in the middle. I'd suggest null, 1 and greater than 1. Maybe test a members count as well.

2023-01-10 19:48 UTC, gbmeuk commented on Google/resource-manager/service_account/provider.tf
> +    google-beta = {
Are we using the beta provider?

2023-01-10 19:48 UTC, gbmeuk commented on tests/gcp/deployment/google_service_account/resource/service_accounts.yaml
> +      disabled: false
Both of these SAs have disabled as false, so not a great test. I'd be inclined to have a service account for each test and name it accordingly. Makes it clearer and more robust.

2023-01-12 22:11 UTC, gbmeuk approved these changes

2023-01-13 10:15 UTC, merged