Deployment test
mesoform/Multi-Cloud-Platform-Foundations pull request #6
Opened 2022-07-28 22:21 UTC by dgavrischuk

Deployment test added
Folders structure changed

2022-08-01 15:44 UTC, AlexBMes requested changes
* The deployment tests should reference the folder module using source. This would involve deleting most of the files in the project and using:
  ```hcl
  module folders {
    source = "../../../../Google/resource-manager/folder/main.tf"
  }
  ```
  to reference to the folder resources. (see comments on files)

* Some of the files in the unit_tests directory should use relative symlinks instead of being a hard copy of the files. (see comments)

* Also if the `project_id` and `folder_id` values in the `folders.yaml` files are real projects and folders, might be better to replace with example id's that don't reference real projects/folders. And in deployment tests to have a value that can be substituted based on Github Secrets. (see comments)

2022-08-01 15:44 UTC, AlexBMes commented on Google/resource-manager/folder/folders.yaml
> +project_id: "decisive-coda-355402"
I don't think this file should be here. If it is here as an example of the structure, I think it should be present in a README. 
Also might be better to use project and folder IDs that don't actually exist i.e just use `project-id` and `folders/1234567`

2022-08-01 15:44 UTC, AlexBMes commented on .github/workflows/deployment_tests.yml
> +      - name: Deploy Google folder
Should add a step before this to configure the files with project and folder IDs retrieved from github secrets. (see [mcp-services deployment tests](https://github.com/mesoform/Multi-Cloud-Platform-Services/blob/main/.github/workflows/deployment_tests.yml#L74-L80))

2022-08-01 15:44 UTC, AlexBMes commented on tests/gcp/deployment/google_folder/locals.tf
> +locals {
Should be deleted if using module structure described in main review comment

2022-08-01 15:44 UTC, AlexBMes commented on tests/gcp/deployment/google_folder/main.tf
> +locals {
Should be replaced with
```hcl
module folders {
  source = "../../../../Google/resource-manager/folder/main.tf"
}
```
As stated in main review comment

2022-08-01 15:44 UTC, AlexBMes commented on tests/gcp/deployment/google_folder/provider.tf
> +terraform {
Should also be deleted as using module block to reference

2022-08-01 15:44 UTC, AlexBMes commented on tests/gcp/deployment/google_folder/resource/folders.yaml
> +project_id: "decisive-coda-355402"
Should be replaced with a string for replacement using `sed`. See [cloudrun.yaml](https://github.com/mesoform/Multi-Cloud-Platform-Services/blob/main/tests/mcp/deployment/GCP/gcp_cloudrun.yml#L1) in mcp-services repo, which gets replaced in [deployment tests step](https://github.com/mesoform/Multi-Cloud-Platform-Services/blob/main/.github/workflows/deployment_tests.yml#L78)

2022-08-01 15:44 UTC, AlexBMes commented on tests/gcp/deployment/google_folder/resource/folders.yaml
> +  parent_id: "folders/227414018885"
This should also be replaced by a folder ID retrieved from a secret in the deployment test.  
@gbmeuk would the secret be called `GCP_FOLDER_ID`?

2022-08-01 15:44 UTC, AlexBMes commented on tests/gcp/deployment/google_folder/vars.tf
> +variable "folders_yml" {
Should also be deleted as using module block to reference

2022-08-01 15:44 UTC, AlexBMes commented on tests/gcp/unit_tests/goole_folder/locals.tf
> +locals {
Should be a relative symlink. I.e.  `../../../../Google/resource-manager/folder/locals.yaml`

2022-08-01 15:44 UTC, AlexBMes commented on tests/gcp/unit_tests/goole_folder/resources/folders.yaml
> +project_id: "decisive-coda-355402"
Should use non existent example project and folder IDs

2022-08-02 00:05 UTC, dgavrischuk commented on Google/resource-manager/folder/folders.yaml
> +project_id: "decisive-coda-355402"
done

2022-08-02 00:05 UTC, dgavrischuk commented on .github/workflows/deployment_tests.yml
> +      - name: Deploy Google folder
done

2022-08-02 00:07 UTC, dgavrischuk commented on tests/gcp/deployment/google_folder/locals.tf
> +locals {
done

2022-08-02 00:07 UTC, dgavrischuk commented on tests/gcp/deployment/google_folder/main.tf
> +locals {
done

2022-08-02 00:13 UTC, dgavrischuk commented on tests/gcp/deployment/google_folder/provider.tf
> +terraform {
done

2022-08-02 00:13 UTC, dgavrischuk commented on tests/gcp/deployment/google_folder/resource/folders.yaml
> +project_id: "decisive-coda-355402"
done

2022-08-02 00:13 UTC, dgavrischuk commented on tests/gcp/deployment/google_folder/resource/folders.yaml
> +  parent_id: "folders/227414018885"
done

2022-08-02 00:14 UTC, dgavrischuk commented on tests/gcp/unit_tests/goole_folder/locals.tf
> +locals {
done

2022-08-02 00:17 UTC, dgavrischuk commented on tests/gcp/deployment/google_folder/vars.tf
> +variable "folders_yml" {
done

2022-08-02 00:21 UTC, dgavrischuk commented on tests/gcp/unit_tests/goole_folder/resources/folders.yaml
> +project_id: "decisive-coda-355402"
done

2022-08-02 09:43 UTC, AlexBMes approved these changes

2022-08-04 08:00 UTC, closed without merging